"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5s!fewuq53zd@%*swfiyi7z9-iu##)yqrbkhvw$a(7zkx2ajnw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.autorizacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Postgres es el motor real del Orquestador (trigger PL/pgSQL de transiciones de
# estado, db-plan-pagos.md 2.2, y DECIMAL(19,2) para montos, sección 4). Mientras
# no haya variables DB_* seteadas, se usa sqlite para poder migrar/probar local
# de inmediato — la migración 0002 detecta el vendor y salta el trigger en ese
# caso (ver esa migración para el detalle de qué deja de estar garantizado).

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Proveedor de pago: BDV Pago Móvil C2P
# https://bdvconciliacionqa.banvenez.com:444 (ambiente Calidad/QA del banco).
# Autenticación por X-API-Key estática, sin token de sesión — ver
# apps/autorizacion/infrastructure/adapters/bdv_c2p.py.

BDV_C2P_BASE_URL = os.environ.get('BDV_C2P_BASE_URL', 'https://bdvconciliacionqa.banvenez.com:444')
BDV_C2P_API_KEY = os.environ.get('BDV_C2P_API_KEY', '')
BDV_C2P_TIMEOUT_SEGUNDOS = int(os.environ.get('BDV_C2P_TIMEOUT_SEGUNDOS', '15'))

# Teléfono afiliado del comercio (Conatel) ante BDV — `commerceNumberInstrument` del
# contrato C2P. Es config del comercio, no algo que la app consumidora deba enviar.
BDV_C2P_TELEFONO_COMERCIO = os.environ.get('BDV_C2P_TELEFONO_COMERCIO', '')


# Token de sesión de checkout (apps/autorizacion/application/services/checkout_token.py):
# emitido por ValidarAccesoView, exigido por los endpoints de cobro en vez de re-derivar
# el dominio de origen del Origin/Referer en cada submit (research-seguridad-iframe.md
# sección 3). Vigencia corta: tiempo esperado para que el usuario reciba el OTP por SMS
# y complete el formulario, no una sesión de checkout larga.
CHECKOUT_TOKEN_MAX_AGE_SEGUNDOS = int(os.environ.get('CHECKOUT_TOKEN_MAX_AGE_SEGUNDOS', '900'))


REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        # Repetirlo solo reenvía el OTP al pagador — el límite existe para no permitir
        # spam de SMS a un número ajeno, no por riesgo de doble cobro.
        'cobro_c2p_otp': '20/hour',
        # Cobro real: más restrictivo que el OTP. Los reintentos legítimos (timeout de
        # red) reusan la misma idempotency_key y no cuentan como una operación nueva
        # del lado del banco, pero sí consumen throttle — el límite deja margen para
        # unos pocos reintentos sin bloquear al usuario a mitad de un pago real.
        'cobro_c2p': '30/hour',
    },
}
