# Generated by Django 6.1 on 2026-08-27 18:24

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
            },
        ),
        migrations.CreateModel(
            name='EventoPagoRecibido',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('procesado_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de pago recibido',
                'verbose_name_plural': 'Eventos de pago recibidos',
            },
        ),
        migrations.CreateModel(
            name='LineaLedger',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'verbose_name': 'Línea de ledger',
                'verbose_name_plural': 'Líneas de ledger',
                'db_table': 'conciliacion_linea_ledger',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('referencia_banco', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('estado_conciliacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliado', 'Conciliado'), ('discrepante', 'Discrepante')], db_index=True, default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
            },
        ),
        migrations.CreateModel(
            name='ReporteERP',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('referencia_externa', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
            ],
            options={
                'verbose_name': 'Reporte ERP',
                'verbose_name_plural': 'Reportes ERP',
            },
        ),
        migrations.CreateModel(
            name='TransaccionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transacción de ledger',
                'verbose_name_plural': 'Transacciones de ledger',
                'db_table': 'conciliacion_transaccion_ledger',
            },
        ),
        migrations.CreateModel(
            name='ConsultaConciliacionProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_corta', models.CharField(db_index=True, max_length=20)),
                ('telefono_pagador', models.CharField(max_length=20)),
                ('cedula_pagador', models.CharField(blank=True, max_length=20)),
                ('cedula_confiable', models.BooleanField(default=False)),
                ('importe_esperado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fecha_pago', models.DateTimeField()),
                ('codigo_respuesta_raw', models.CharField(max_length=20)),
                ('mensaje_respuesta_raw', models.TextField(blank=True)),
                ('resultado_interpretado', models.CharField(choices=[('conciliado', 'Conciliado'), ('no_encontrado', 'No encontrado'), ('monto_no_coincide', 'Monto no coincide'), ('ya_conciliado', 'Ya conciliado'), ('error_credenciales', 'Error de credenciales'), ('pendiente_revision', 'Pendiente de revisión')], max_length=30)),
                ('payload_crudo', models.JSONField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_conciliacion', to='conciliacion.banco')),
            ],
            options={
                'verbose_name': 'Consulta de conciliación al proveedor',
                'verbose_name_plural': 'Consultas de conciliación al proveedor',
            },
        ),
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('sin_movimiento_bancario', 'Sin movimiento bancario'), ('monto_no_coincide', 'Monto no coincide'), ('duplicado', 'Duplicado'), ('error_proveedor', 'Error del proveedor'), ('pendiente_revision_manual', 'Pendiente de revisión manual')], max_length=30)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('estado_resolucion', models.CharField(choices=[('abierta', 'Abierta'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], db_index=True, default='abierta', max_length=15)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias', to='conciliacion.consultaconciliacionproveedor')),
            ],
            options={
                'verbose_name': 'Discrepancia',
                'verbose_name_plural': 'Discrepancias',
            },
        ),
    ]
