# Generated by Django 6.1 on 2026-08-27 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conciliacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancia',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discrepancia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias', to='conciliacion.eventopagorecibido'),
        ),
        migrations.AddField(
            model_name='consultaconciliacionproveedor',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_conciliacion', to='conciliacion.eventopagorecibido'),
        ),
        migrations.AddField(
            model_name='linealedger',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_ledger', to='conciliacion.cuentacontable'),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='conciliacion.banco'),
        ),
        migrations.AddField(
            model_name='discrepancia',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias', to='conciliacion.movimientobancario'),
        ),
        migrations.AddField(
            model_name='transaccionledger',
            name='referencia_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_ledger', to='conciliacion.eventopagorecibido'),
        ),
        migrations.AddField(
            model_name='linealedger',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='conciliacion.transaccionledger'),
        ),
        migrations.AddIndex(
            model_name='discrepancia',
            index=models.Index(fields=['estado_resolucion', 'severidad'], name='conciliacio_estado__9c5a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='linealedger',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='linea_ledger_monto_positivo'),
        ),
    ]
