# Generated by Django 6.1 on 2026-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0003_ledger_balance_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaconciliacionproveedor',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
