# Generated by Django 6.0.6 on 2026-08-27 15:12

import apps.autorizacion.domain.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionRegistrada',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('app_origen_id', models.UUIDField(help_text='Id lógico de AppConsumidora en el Developer Portal (sin FK real, sistema externo).', unique=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Aplicación registrada',
                'verbose_name_plural': 'Aplicaciones registradas',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, help_text='Código SUDEBAN/BCV de 4 dígitos.', max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.UUIDField(db_index=True, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=15)),
                ('expires_at', models.DateTimeField(default=apps.autorizacion.domain.models.default_expiracion_idempotency_key)),
            ],
            options={
                'verbose_name': 'Clave de idempotencia',
                'verbose_name_plural': 'Claves de idempotencia',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='DominioPermitido',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dominio', models.CharField(db_index=True, max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='autorizacion.aplicacionregistrada')),
            ],
            options={
                'verbose_name': 'Dominio permitido',
                'verbose_name_plural': 'Dominios permitidos',
            },
        ),
        migrations.CreateModel(
            name='IntencionPago',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('estado_actual', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('capturado', 'Capturado'), ('anulado', 'Anulado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('expirado', 'Expirado')], db_index=True, default='pendiente', max_length=15)),
                ('routing_flag', models.CharField(choices=[('legacy', 'Legacy'), ('canario', 'Canario')], default='legacy', max_length=10)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intenciones_pago', to='autorizacion.aplicacionregistrada')),
                ('idempotency_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intencion_pago', to='autorizacion.idempotencykey')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intenciones_pago', to='autorizacion.mediopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intenciones_pago', to='autorizacion.moneda')),
            ],
            options={
                'verbose_name': 'Intención de pago',
                'verbose_name_plural': 'Intenciones de pago',
            },
        ),
        migrations.CreateModel(
            name='EventoOutbox',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], db_index=True, default='pendiente', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_outbox', to='autorizacion.intencionpago')),
            ],
            options={
                'verbose_name': 'Evento de outbox',
                'verbose_name_plural': 'Eventos de outbox',
            },
        ),
        migrations.CreateModel(
            name='ProveedorPago',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='autorizacion.mediopago')),
            ],
            options={
                'verbose_name': 'Proveedor de pago',
                'verbose_name_plural': 'Proveedores de pago',
            },
        ),
        migrations.CreateModel(
            name='CodigoRespuestaProveedor',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('exito', 'Éxito'), ('duplicado_idempotente', 'Duplicado idempotente'), ('error_negocio', 'Error de negocio'), ('error_tecnico', 'Error técnico')], db_index=True, max_length=25)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_respuesta', to='autorizacion.proveedorpago')),
            ],
            options={
                'verbose_name': 'Código de respuesta de proveedor',
                'verbose_name_plural': 'Códigos de respuesta de proveedor',
            },
        ),
        migrations.CreateModel(
            name='AplicacionProveedorPermitido',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('autorizado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_autorizados', to='autorizacion.aplicacionregistrada')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_autorizadas', to='autorizacion.proveedorpago')),
            ],
            options={
                'verbose_name': 'Autorización aplicación-proveedor',
                'verbose_name_plural': 'Autorizaciones aplicación-proveedor',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacionProveedor',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_operacion', to='autorizacion.proveedorpago')),
            ],
            options={
                'verbose_name': 'Tipo de operación de proveedor',
                'verbose_name_plural': 'Tipos de operación de proveedor',
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_proveedor', models.CharField(max_length=100)),
                ('referencia_corta', models.CharField(blank=True, max_length=20)),
                ('identificador_interbancario', models.CharField(blank=True, max_length=62)),
                ('payload_crudo', models.JSONField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('codigo_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='autorizacion.codigorespuestaproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='autorizacion.intencionpago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='autorizacion.proveedorpago')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='autorizacion.tipooperacionproveedor')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
            },
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_proveedor', models.CharField(max_length=100)),
                ('referencia_corta', models.CharField(blank=True, max_length=20)),
                ('identificador_interbancario', models.CharField(blank=True, max_length=62)),
                ('payload_crudo', models.JSONField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('codigo_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='autorizacion.codigorespuestaproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='autorizacion.intencionpago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='autorizacion.proveedorpago')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='autorizacion.tipooperacionproveedor')),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
            },
        ),
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_proveedor', models.CharField(max_length=100)),
                ('referencia_corta', models.CharField(blank=True, max_length=20)),
                ('identificador_interbancario', models.CharField(blank=True, max_length=62)),
                ('payload_crudo', models.JSONField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('otp_solicitado_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='autorizacion.codigorespuestaproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='autorizacion.intencionpago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='autorizacion.proveedorpago')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='autorizacion.tipooperacionproveedor')),
            ],
            options={
                'verbose_name': 'Autorización',
                'verbose_name_plural': 'Autorizaciones',
            },
        ),
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_proveedor', models.CharField(max_length=100)),
                ('referencia_corta', models.CharField(blank=True, max_length=20)),
                ('identificador_interbancario', models.CharField(blank=True, max_length=62)),
                ('payload_crudo', models.JSONField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('codigo_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones', to='autorizacion.codigorespuestaproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anulaciones', to='autorizacion.intencionpago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones', to='autorizacion.proveedorpago')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones', to='autorizacion.tipooperacionproveedor')),
            ],
            options={
                'verbose_name': 'Anulación',
                'verbose_name_plural': 'Anulaciones',
            },
        ),
        migrations.CreateModel(
            name='TransicionEstadoPago',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('capturado', 'Capturado'), ('anulado', 'Anulado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('expirado', 'Expirado')], max_length=15, null=True)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('capturado', 'Capturado'), ('anulado', 'Anulado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('expirado', 'Expirado')], max_length=15)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones', to='autorizacion.intencionpago')),
            ],
            options={
                'verbose_name': 'Transición de estado de pago',
                'verbose_name_plural': 'Transiciones de estado de pago',
            },
        ),
        migrations.AddConstraint(
            model_name='codigorespuestaproveedor',
            constraint=models.UniqueConstraint(fields=('proveedor', 'codigo'), name='uniq_codigo_respuesta_proveedor_codigo'),
        ),
        migrations.AddConstraint(
            model_name='aplicacionproveedorpermitido',
            constraint=models.UniqueConstraint(fields=('aplicacion', 'proveedor'), name='uniq_aplicacion_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='tipooperacionproveedor',
            constraint=models.UniqueConstraint(fields=('proveedor', 'codigo'), name='uniq_tipo_operacion_proveedor_codigo'),
        ),
        migrations.AddIndex(
            model_name='transicionestadopago',
            index=models.Index(fields=['pago', '-created_at'], name='idx_transicion_pago_created'),
        ),
    ]
