# Generated by Django 6.0.6 on 2026-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0004_seed_catalogos_bdv_c2p'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventooutbox',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='ultimo_intento_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
