# Generated by Django 6.0.6 on 2026-08-29 17:17

import apps.autorizacion.domain.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0005_evento_outbox_reintentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutTokenConsumido',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_tokens_consumidos', to='autorizacion.intencionpago')),
            ],
            options={
                'verbose_name': 'Checkout token consumido',
                'verbose_name_plural': 'Checkout tokens consumidos',
            },
        ),
    ]
