# Generated by Django 6.0.6 on 2026-08-29 17:33

import apps.autorizacion.domain.campos_cifrados
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0006_checkout_token_consumido'),
    ]

    operations = [
        # Filas existentes con JSON en claro no son un token Fernet válido — el
        # ALTER de tipo jsonb->text de abajo las dejaría ilegibles al primer
        # intento de descifrado (InvalidToken). Solo hay datos de prueba/dev en
        # estas columnas hoy (no producción real todavía) — se limpian antes de
        # cambiar el tipo de columna, en vez de intentar "cifrar en caliente"
        # datos que ya estaban en claro sin la garantía real de esa protección.
        # response_snapshot es nullable (se vacía); payload_crudo/payload de
        # Autorizacion/Captura/Anulacion/Reembolso/EventoOutbox NO lo son — se
        # borran las filas enteras (encontrado en vivo: una fila real de
        # EventoOutbox de una prueba anterior quedó ilegible con solo el UPDATE
        # de response_snapshot).
        migrations.RunSQL(
            sql="""
                UPDATE autorizacion_idempotencykey SET response_snapshot = NULL WHERE response_snapshot IS NOT NULL;
                DELETE FROM autorizacion_anulacion;
                DELETE FROM autorizacion_reembolso;
                DELETE FROM autorizacion_captura;
                DELETE FROM autorizacion_autorizacion;
                DELETE FROM autorizacion_eventooutbox;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='anulacion',
            name='payload_crudo',
            field=apps.autorizacion.domain.campos_cifrados.EncryptedJSONField(),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='payload_crudo',
            field=apps.autorizacion.domain.campos_cifrados.EncryptedJSONField(),
        ),
        migrations.AlterField(
            model_name='captura',
            name='payload_crudo',
            field=apps.autorizacion.domain.campos_cifrados.EncryptedJSONField(),
        ),
        migrations.AlterField(
            model_name='eventooutbox',
            name='payload',
            field=apps.autorizacion.domain.campos_cifrados.EncryptedJSONField(),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='response_snapshot',
            field=apps.autorizacion.domain.campos_cifrados.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='payload_crudo',
            field=apps.autorizacion.domain.campos_cifrados.EncryptedJSONField(),
        ),
    ]
