# Generated by Django 6.0.6 on 2026-08-30 18:59

import apps.autorizacion.domain.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0007_campos_cifrados'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionregistrada',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aplicacionregistrada',
            name='webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='WebhookEntrega',
            fields=[
                ('id', models.UUIDField(default=apps.autorizacion.domain.models.generar_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('agotado', 'Agotado')], db_index=True, default='pendiente', max_length=15)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_intento_at', models.DateTimeField(blank=True, null=True)),
                ('ultima_respuesta_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_entrega', to='autorizacion.eventooutbox')),
            ],
            options={
                'verbose_name': 'Entrega de webhook',
                'verbose_name_plural': 'Entregas de webhook',
            },
        ),
    ]
